hooks:
  #if plugin is load, if not, there options are useless
  placeholder-api: true


api:
  website_url: "https://edensky.fr"
  #paste here your public key, get it on website (this is an example)
  private_key: "-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDSxqe/XX3ROrvR
BrH7rR1WlfOjvzqY+3OKiVvr3WJRWID4lygSbDxz7X18pEIw+OyyEK3A1UijhvGL
.....
LzQvPzJ2nHBRRwjrXRo7cqEGBumELPdaPvNtTf5mCjqDTMnheCHoWd56+wvL85ii
OpxYOcxxb3hUv0KYII2b2g==
-----END PRIVATE KEY-----"
