#
# MySQL settings.
#
database:
    host: "localhost"
    username: "root"
    password: ""
    database: "mineweb"
    #default = 3306
    port: 3306
    
hooks:
    #if plugin is load, if not, there options are useless
    placeholder-api: true
    mvdwplaceholder-api: true
