name: Pointz
version: 2.6.8
author: nivcoo
main: fr.nivcoo.pointz.Pointz
softdepend: [ PlaceholderAPI ]
api-version: 1.13
commands:
  pointz:
    description: List of commands
permissions:
  pointz.commands:
    default: op
    description: Pointz Command
  pointz.command.send:
    default: op
    description: Send money
  pointz.command.manage.set:
    default: op
    description: Manage player
  pointz.command.manage.add:
    default: op
    description: Manage player
  pointz.command.manage.del:
    default: op
    description: Manage player
  pointz.command.check:
    default: op
    description: Check money
  pointz.command.gui.converter:
    default: op
    description: Converter IG
  pointz.command.gui.shop:
    default: op
    description: Shop IG