###################################################################

#Points

#Config v6.0
###################################################################

host: "localhost"
name: "root"
pass: "pass"
dbName: "mineweb"
port: 3306

