name: Pointz
version: 0.0.1
author: nivcoo
main: fr.nivcoo.pointz.Pointz
commands:
  points:
    description: List of commands
  pshop:
    description: shop
  pgui:
    description: gui
permissions:
  pointz.command:
    default: op
    description: /points list
  pointz.send:
    default: op
    description: Send money
  pointz.manage:
    default: op
    description: Add/del/set Money
  pointz.check:
    default: op
    description: Check money
  pointz.gui:
    default: op
    description: Check money
  pointz.shop:
    default: op
    description: Shop IG