name: Pointz
version: 0.0.5
author: nivcoo
main: fr.nivcoo.pointz.Pointz
softdepend: [MVdWPlaceholderAPI]
commands:
  pointz:
    description: List of commands
  pshop:
    description: shop
  pconverter:
    description: converter
permissions:
  pointz.command:
    default: op
    description: /points list
  pointz.send:
    default: op
    description: Send money
  pointz.manage:
    default: op
    description: Add/del/set Money
  pointz.check:
    default: op
    description: Check money
  pointz.converter:
    default: op
    description: Converter IG
  pointz.shop:
    default: op
    description: Shop IG